{{- if .Values.enabled }}
{{- if .Values.rest }}
{{- if .Values.ingress.rest.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}-rest
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  annotations:
    {{- range $key, $value := .Values.ingress.rest.annotations }}
      {{- if not (eq $key "nil") }}
    {{ $key }}: {{ $value | quote }}
      {{- end }}
    {{- end }}
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.rest.path }}
        backend:
          serviceName: {{ .Values.name }}-rest
          servicePort: {{ .Values.ingress.rest.servicePort }}
{{- end }}
{{- end }}
{{- end }}

