###############################
# DEFAULT 
###############################
enabled: true
developer: false
grpc: true
scheduler: false
worker: false
rest: false
name: monitoring
replicas: 1
image:
    name: spaceone/monitoring
    version: latest
imagePullPolicy: IfNotPresent

# Overwrite database
database: {}

# Overwrite application config
application: {}

# Overwrite application rest config
application_rest: {}

# Overwrite scheduler config
application_scheduler:
  SCHEDULERS:
    monitoring_scheduler:
      backend: spaceone.monitoring.interface.task.v1.monitoring_alert_scheduler.MonitoringAlertScheduler
      queue: monitoring_q
      interval: 60
    maintenance_window_scheduler:
      backend: spaceone.monitoring.interface.task.v1.maintenance_window_scheduler.MaintenanceWindowScheduler
      queue: monitoring_q
      interval: 60

# Overwrite worker config
application_worker:
  WORKERS:
    monitoring_worker:
      backend: spaceone.core.scheduler.worker.BaseWorker
      queue: monitoring_q
      pool: 1

# local sidecar
##########################
#sidecar:


##########################
# Local volumes
##########################
volumes:
    - name: timezone
      hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
    - name: log-volume
      emptyDir: {}

#######################
# global variable
#######################
global:
    shared: {}
    sidecar: []
#        - name: mongos
#          image: mongo:4.4.0-bionic
#          command: [ 'mongos', '--config', '/mnt/mongos.yml', '--bind_ip_all' ]
#          volumeMounts:
#            - name: mongos-conf
#              mountPath: /mnt/mongos.yml
#              subPath: mongos.yml
#              readOnly: true
#            - name: mongo-shard-key
#              mountPath: /opt/mongos/mongo-shard.pem
#              subPath: mongo-shard.pem
#              readOnly: true
#
    volumes: []
#        - name: mongo-shard-key
#          secret:
#              defaultMode: 0400
#              secretName: mongo-shard-key
#        - name: mongos-conf
#          configMap:
#              name: mongos-conf
#        - name: shared-conf
#          configMap:
#              name: shared-conf

    
# Service
service:
    grpc:
        type: ClusterIP
        annotations:
            nil: nil
        ports:
            - name: grpc
              port: 50051
              targetPort: 50051
              protocol: TCP

################################
# volumeMount per deployment
################################
volumeMounts:
    application_grpc: []
    application_rest: []
    application_scheduler: []
    application_worker: []

####################################
# pod spec (append more pod spec)
# example nodeSelect
#
# pod:
#   spec:
#     nodeSelector:
#       application: my-node-group
####################################
pod:
    spec: {}
